version: '2'
services:
  server:
    build: .
    ports:
     - "3322:22"
     - "8080:80"
    volumes:
      - ./data/webapp:/home/app/webapp
      - ./data/ssh:/home/app/.ssh

# docker-compose -f docker-compose.dev.yml up --build